name: Autocode
on:
  issues:
    types: [labeled]

env:
  MODEL: "claude-3-5-sonnet-20241022"
  MAX_TOKENS: 4000

jobs:
  create-pr:
    runs-on: ubuntu-latest
    if: contains(github.event.issue.labels.*.name, 'autocode')
    steps:
      - uses: actions/checkout@v4

      - name: Setup bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Run autocode action
        env:
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_EVENT_ISSUE_NUMBER: ${{ github.event.issue.number }}
          GITHUB_REPO_FULL: ${{ github.repository }}
        run: bun i && bun run src/index.ts

      - name: Handle errors
        if: failure()
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: '❌ The autocode action failed to process this issue. Please check the action logs for details.'
            })
